---
apiVersion: v1
kind: Service
metadata:
  name: api-collector
spec:
  selector:
    app: api-collector
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-collector
  labels:
    app: api-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-collector
  template:
    metadata:

      labels:
        app: api-collector
    spec:
      containers:
        - name: api-collector
          image: 172.18.255.1:5000/api-collector
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
          volumeMounts:
          - name: workload-security-credentials
            mountPath: "/etc/workload-security-credentials"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: workload-security-credentials
          secret:
            secretName: workload-security
