---
apiVersion: v1
kind: Service
metadata:
  name: api-collector
spec:
  selector:
    app: api-collector
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
# kubectl -n prometheus  create secret docker-registry regcred --docker-server=172.18.255.1:5000 --docker-username=admin --docker-password=trendmicro --docker-email=info@mail.com --dry-run=client -o yaml
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxNzIuMTguMjU1LjE6NTAwMCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJ0cmVuZG1pY3JvIiwiZW1haWwiOiJpbmZvQG1haWwuY29tIiwiYXV0aCI6IllXUnRhVzQ2ZEhKbGJtUnRhV055Ync9PSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: prometheus
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: workload-security
type: Opaque
data:
  ws_url: YXBwLmRlZXBzZWN1cml0eS50cmVuZG1pY3JvLmNvbTo0NDM=
  api_key: RTBCNzcyRkEtMUMxOC1DNjE1LTc0QUMtN0I3RTQ0RTVFMTlFOjY0M0IzMzg2LTIyQ0MtRTZFNy1DQUFCLTQ3OTg3NjEyNUQ0NDoyQ1h3NFZPZjVVbmZOMnlFSWFhNGoza1VDRW9WTDVsRm5YZ0gydHBwUlQ0PQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-collector
  labels:
    app: api-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-collector
  template:
    metadata:

      labels:
        app: api-collector
    spec:
      containers:
        - name: api-collector
          image: 172.18.255.1:5000/api-collector
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
          volumeMounts:
          - name: workload-security-credentials
            mountPath: "/etc/workload-security-credentials"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: workload-security-credentials
          secret:
            secretName: workload-security
