{
 "title": "Cloud One",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Smart Check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container Memory Usage Bytes Scanner Pods",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"smartcheck\", pod=~\".*scan.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage Bytes Registry Pods",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"smartcheck\", pod=~\".*registry.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage Seconds Total Scanner Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod!=\"\", pod=~\".*scan.*\", namespace=\"smartcheck\"}[5m]) * 100) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage Seconds Total Registry Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod!=\"\", pod=~\".*registry.*\", namespace=\"smartcheck\"}[5m]) * 100) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Network RX Bytes Total Scanner Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{pod=~\".*scan.*\", namespace=\"smartcheck\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Network TX Bytes Total Scanner Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{pod=~\".*scan.*\", namespace=\"smartcheck\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Network RX Bytes Total Registry Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{pod=~\".*registry.*\", namespace=\"smartcheck\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Network TX Bytes Total Registry Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{pod=~\".*registry.*\", namespace=\"smartcheck\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Network RX Bytes Total Cluster Registry",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{pod=~\".*registry.*\", namespace=\"registry\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Network TX Bytes Total Cluster Registry",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{pod=~\".*registry.*\", namespace=\"registry\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "AstroWeather", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Astroweather Sky Quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "astroweather_total{timepoint=\"21:00\"}",
     "legendFormat": "21:00"
    },
    {
     "expr": "astroweather_total{timepoint=\"00:00\"}",
     "legendFormat": "00:00"
    },
    {
     "expr": "astroweather_total{timepoint=\"03:00\"}",
     "legendFormat": "03:00"
    }
   ]
  },
  { "title": "Application Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Settings Mitigate",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(as_settings_total{setting!=\"info\"}) by (setting)",
     "legendFormat": "{{setting}}"
    }
   ]
  },
  {
   "title": "Security Goup Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(as_settings_total{setting=\"info\"})",
     "legendFormat": "Security Groups"
    }
   ]
  },
  { "title": "File Storage Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Daily Malware Findings vs. Scans",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fss_statistics_total{statistic=~\"detections|scans\"}) by (statistic)",
     "legendFormat": "{{statistic}}"
    }
   ]
  },
  {
   "title": "Malware Discovery Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fss_statistics_total{statistic=\"detections\"}) / sum(fss_statistics_total{statistic=\"scans\"}) * 100",
     "legendFormat": "Malware Discovery Percentage"
    }
   ]
  },
  {
   "title": "Stacks Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fss_statistics_total{statistic=\"scanner_stacks\"}",
     "legendFormat": "Scanner Stacks"
    },
    {
     "expr": "fss_statistics_total{statistic=\"storage_stacks\"}",
     "legendFormat": "Storage Stacks"
    }
   ]
  },
  { "title": "Workload Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Agent Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ws_ips_total{arribute=\"info\"}) by (agentStatus)",
     "legendFormat": "{{agentStatus}}"
    }
   ]
  },
  {
   "title": "Agent Update Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ws_ips_total{arribute=\"info\"}) by (updateStatus)",
     "legendFormat": "{{updateStatus}}"
    }
   ]
  },
  {
   "title": "Agent Versions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ws_ips_total{agentVersion!=\"0.0.0.0\",arribute=\"info\"}) by (agentVersion)",
     "legendFormat": "{{agentVersion}}"
    }
   ]
  },
  {
   "title": "Protected Vulnerabilities by Platform",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ws_ips_total{arribute=\"type_vulnerability\"}) by (platform) != 0",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "Protected Exploits by Platform",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ws_ips_total{arribute=\"type_exploit\"}) by (platform) != 0",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "IPS Rules by Platform",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ws_ips_total{arribute=\"rule_count\"}) by (platform) != 0",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "Cloud Provider Instance Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ws_ips_total{arribute=\"info\"}) by (cloud_provider)",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "IPS Rule Count by Platform",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ws_ips_total{arribute=\"rule_count\"}) by (platform) != 0",
     "legendFormat": "{{platform}}"
    }
   ]
  }
 ]
}