apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-collector
  labels:
    app: api-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-collector
  template:
    metadata:

      labels:
        app: api-collector
    spec:
      containers:
      - name: api-collector
        image: 172.18.255.1:5000/api-collector
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: regcred